### ISSUE TITLE
Error report version 2.4.2.1440

### ISSUE THREAD

**Issue by kwibus2000** [simonsteele/pn#135]
Hello Mr. Steele,

Do you see the image? Is this a bug?

However, I am glad to see you're working on a new version; PN2 has been my editor of choice for many moons, now!
![programmers notepad](https://cloud.githubusercontent.com/assets/10372060/20970786/4ffbc3b2-bc8f-11e6-8dbd-1ecb8fb3605b.jpg)

**Comment by simonsteele** [comment]
Thanks for this, sorry you're seeing it. This happens when a ".cscheme" has not been correctly rebuilt by the current version - this usually means that a scheme is no longer present in your installation. If you keep seeing it, try removing all the .cscheme files from your user settings folder and restarting: http://www.pnotepad.org/docs/settings_storage/
