### ISSUE TITLE
After automatic update and reinstallation - CRASH

### ISSUE THREAD

**Issue by mankaf** [simonsteele/pn#137]
After upgrade to new version 2.4.2.1440 , PN crashes with loads of warning messages.

ie: 

Unexpected error in file : appsettings.cpp, line: 300 version ......
Please post this to the forum or file a bug.

extapp.cpp, line: 138

SchemaCompiller.cpp, line: 352

and on, and on and on, pretty desperate I had to install notapad++ as I need to work on ....

Please tell me its just me and I made some mistake.

OS: Windows 10  Pro 64bit

Best regards Miro.

**Comment by simonsteele** [comment]
Sorry to hear that! Could you try running without plugins and see if that helps: 

`pn --safemode`

If it's this, it may be that one of the plugins installed is no longer compatible with the new version and I missed it. Let me know!

**Comment by mankaf** [comment]
Thank you for your rapid reply, but unfortunately it is the same

![image](https://cloud.githubusercontent.com/assets/16303901/21140026/2b4ba07c-c136-11e6-95dd-3c00b626b621.png)

**Comment by simonsteele** [comment]
Interesting, it says it couldn't create a user settings directory. Is your system locked down in some way, and had you perhaps used the portable version before?

If you had portable before, you could try dropping this file in the PN directory:

https://github.com/simonsteele/pn/blob/master/pnwtl/installer/configs/portable/config.xml

this will make it use the specified directory (e.g. settings) to store settings rather than relying on your user settings directory.

**Comment by mankaf** [comment]
Well,

I tried what you suggested, put the config file in the PN portable directory.

Found out there were some issues regarding the access to the Program Files folder.

More or less after movin the whole PN folder to the Desktop looks like it is working again.

Pitty it was working before in the Program Files (x86) and not after the upgrade / unzip portable PN files to PN folder.

Anyway thank you for help! I am back with PN !!
