### ISSUE TITLE
Powershell scheme doesn't color-highlight correctly, also comment/uncomment doesn't work

### ISSUE THREAD

**Issue by rocketmonkeys** [simonsteele/pn#16]
The default powershell scheme file has .scheme extension, and doesn't seem to highlight ps1 files correctly for me.  Renaming the file to .schemedef appears to work (code is color-highlighted correctly).

Also, the Edit>Comments items are disabled, so I can't automatically comment/uncomment code, which is a bummer.  There is this in the .scheme file:

		<comments>
			<line start="#" />
		</comments>

That helps highlight comments, but still can't add/remove them with PN.  I added this:

            <block start="&lt;#" end="&lt;" />

Which helps w/ block comments.

Where do I start to figure out how to enable comment/uncomment via scheme in PN?  Thanks!		

v2.4.0.2378-duke.

**Comment by simonsteele** [comment]
This is a bit confusing, because the default powershell scheme that should be included is not a schemedef (though there was a previous version that was, so perhaps that's the issue).

You should have this file as powershell.scheme:

https://github.com/simonsteele/pn/blob/master/pnwtl/bin/schemes/powershell.scheme

Using that, commenting works for me, though it had the wrong character for line comments. I've just committed a minor improvement that fixes this and adds comment stream support.

Once you've made sure that's the only powershell scheme you have, make sure that it's selected for .ps1 files in the Files section of Options.
