### ISSUE TITLE
The Line Numbers setting is not being saved when closing the program

### ISSUE THREAD

**Issue by life777eternal** [simonsteele/pn#201]
The option to show the Line Numbers under the View Menu is not being saved when closing the program. Also I have to select it again every time I drag a file into Programmer's Notepad to edit it. 

Also it would be nice if you could place the "Close" 'X' for each tab on each tab, instead of to the far right. As it is on Notepad++.

Additionally, I'm not sure why the extra Minimize, Restore Down, and Close buttons are needed at the top right, or if that feature is even used anymore. 

Oh and this is on Windows Web Server 2008 R2, which is similar to Windows 7. 

Thank you.

**Comment by veganaiZe** [comment]
Maybe try running the program as an Administrator?  That should allow your (line numbering) options to be saved.

You can right-click on a tab to find a "Close" option at the top of a context menu or, alternatively, double-clicking a tab will also close it.  I personally prefer these methods, over the 'X', because it's often times a little too easy to accidentally click an 'X' on a tab.

The 'extra' minimize / restore / close buttons are there because each editing 'window' is actually an MDI child window, confined within the Programmer's Notepad 'parent' window.  In other words, each of the editor's tabs/windows can be independently minimized, restored, or closed.  That used to be pretty much the only way to allow multiple documents to be edited simultaneously, in Windows, before tabs became a thing.  On the upside, this allows you to do things like selecting Window -> Tile Vertical which is probably most ideal when only two (maybe three) tabs are open.

**Comment by life777eternal** [comment]
Running it as an Administrator doesn't save the line numbers. The account on my Server is already the Administrator account, though even when I Right-Click on Programmer's Notepad and hit "Run as administrator" and turn on the line numbers, and close it, the next time I open it normally the line numbers are gone again. Is the Line Numbers setting specific for each child window in Programmer's Notepad? Because when I close the child 'window' in Programmer's Notepad, the options in the "View" menu is reduced and I don't see a Line numbers option. 

This is the View Menu in a bare-bones state without any child window. 

![2021-09-07 12_38_53 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/132394838-cd39824e-9ffc-4d96-ba48-9edfe046759e.png)

This is the View Menu after I click on the 'New' button below there to the left. Opening Programmer's Notepad from the Start Menu has the same result. 

![2021-09-07 12_39_32 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/132394959-06535d47-a548-42d9-aec3-fe363c260ea4.png)



Also I see what you mean about the 'X' for each tab, although I haven't really accidentally clicked the 'X' on the tabs in Notepad++.

Alright, I can live with the secondary minimize/restore/close buttons being there, and that's not a bad feature.

**Comment by veganaiZe** [comment]
You're right about the `View` -> `Line Numbers`!  It only affects the individual tab.  Apparently you must set `Tools` -> `Options` -> `General` -> `Defaults` -> `Show Line Numbers`. 

![linenum](https://user-images.githubusercontent.com/7102064/132403670-76d3836f-f681-4769-bdc8-7068a207ef4b.png)

If, for some reason, that doesn't work then try launching with the `--reset` command line argument.  _I'd try it as both administrator and regular user.  The application might not get administrator privileges unless you specifically select "Run as administrator", even though your user account has administrator privileges._

**Comment by life777eternal** [comment]
Oh I see, alright, thank you. That did work.
